<html>
<head>
<title>custom_excepthook.py</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
.s0 { color: #cc7832;}
.s1 { color: #a9b7c6;}
.s2 { color: #6a8759;}
.s3 { color: #808080;}
</style>
</head>
<body bgcolor="#2b2b2b">
<table CELLSPACING=0 CELLPADDING=5 COLS=1 WIDTH="100%" BGCOLOR="#606060" >
<tr><td><center>
<font face="Arial, Helvetica" color="#000000">
custom_excepthook.py</font>
</center></td></tr></table>
<pre><span class="s0">import </span><span class="s1">_common</span>

<span class="s0">import </span><span class="s1">sys</span>


<span class="s0">def </span><span class="s1">custom_excepthook(*args):</span>
    <span class="s1">print(</span><span class="s2">&quot;custom running!&quot;</span><span class="s1">)</span>
    <span class="s0">return </span><span class="s1">sys.__excepthook__(*args)</span>


<span class="s1">sys.excepthook = custom_excepthook</span>

<span class="s3"># Should warn that we'll get kinda-broken tracebacks</span>
<span class="s0">import </span><span class="s1">trio</span>

<span class="s3"># The custom excepthook should run, because Trio was polite and didn't</span>
<span class="s3"># override it</span>
<span class="s0">raise </span><span class="s1">trio.MultiError([ValueError()</span><span class="s0">, </span><span class="s1">KeyError()])</span>
</pre>
</body>
</html>